LANGUAGE {English/ANSI}

LEVEL6 {}

STARTUP {Cool ass module starting up} T Startup message

INTRO {Welcome to my cool game
} T Intro

PROMPT {Type something: } T Prompt

OUTPUT {You entered: } T Output

MENU {[1;32mPlease select one of the following: 

   [1;36mE [1;33m... Echo
   [1;36mT [1;33m... Timing
   [1;36mS [1;33m... FPU Tests
   [1;36mF [1;33m... Full Screen Editor
   [1;36mD [1;33m... Full Screen Data Editor
   
[1;36mMake your selection (E, T, S, F, D, or X to exit): } T Menu

TMRINT {Initiating the timers, x to exit module...
} T Timer Intro

TMROUT {Timer has fired! %d:%d rti:%d
} T Timer

FLTOUT {Float value is: %s
Double value is: %s
} T Float Print

LEVEL99 {}


FSE {[0;1;32m
                  User Account Information
                  ------------------------
        User-ID:  [36m?????????????????????????????[32m

           Name:  [33m?????????????????????????????[32m
        Company:  [33m?????????????????????????????[32m
 Address line 1:  [33m?????????????????????????????[32m
 Address line 2:  [33m?????????????????????????????[32m
 Address line 3:  [33m?????????????????????????????[32m
   Phone Number:  [33m???????????????[32m

Computer system:  [33m?????????????[32m  ANSI-[33m????[32m
    Screen size:  [33m$$$[32m columns  [33m$$$[32m lines
 Default editor:  [33m????[32m
   Pause output?  [33m??????????[32m

           Born:  [33m????????[32m
            Sex:  [33m??????[32m
       Password:  [33m?????????[32m

           Exit:  [37m????[32m  [0;32m(select SAVE or QUIT and press ENTER)[1m

       [31m!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!![32m} T User Information Editing - for ANSI users

