LEVEL0 {MBBSEmu Test MSG File for MajorMUD Scenarios}

LEVEL1 {Hardware Setup Options}

LEVEL3 {Security and Accounting Options}

LEVEL4 {Configuration Options}

TEST1{This is topic 1: value} S 30 Help Topic String

LEVEL6 {Text Editable Blocks}

TEST2 {This is topic 2: value} S 30 Help Topic 2

String

TEST3 {This is topic 3: value} S 40 Help Topic 3 String

TEST4 {Escaped ~~ Values ~} Test}

LEVEL8 {FSE Help Messages}