namespace MBBSEmu.Telnet
{
    public enum EnumIacOptions : byte
    {
        BinaryTransmission = 0,
        Echo = 1,
        Reconnection = 2,
        SuppressGoAhead = 3,
        ApproxMessageSizeNegotiation = 4,
        Status = 5,
        TimingMark = 6,
        RemoteControlledTransAndEcho = 7,
        OutputLineWidth = 8,
        OutputPageSize = 9,
        OutputCarriageReturnDisposition = 10,
        OutputHorizontalTabStops = 11,
        OutputHorizontalTabDisposition = 12,
        OutputFormfeedDisposition = 13,
        OutputVerticalTabStops = 14,
        OutputVerticalTabDisposition = 15,
        OutputLinefeedDisposition = 16,
        ExtendedASCII = 17,
        Logout = 18,
        ByteMacro = 19,
        DataEntryTerminal = 20,
        SUPDUP = 21,
        SUPDUPOutput = 22,
        SendLocation = 23,
        TerminalType = 24,
        EndOfRecord = 25,
        TACACSUserIdentification = 26,
        OutputMarking = 27,
        TerminalLocationNumber = 28,
        Telnet3270Regime = 29,
        X3PAD = 30,
        NegotiateAboutWindowSize = 31,
        TerminalSpeed = 32,
        RemoteFlowControl = 33,
        Linemode = 34,
        XDisplayLocation = 35,
        EnvironmentOption = 36,
        AuthenticationOption = 37,
        EncryptionOption = 38,
        NewEnvironmentOption = 39,
        TN3270E = 40,
        XAUTH = 41,
        CHARSET = 42,
        TelnetRemoteSerialPort = 43,
        ComPortControlOption = 44,
        TelnetSuppressLocalEcho = 45,
        TelnetStartTLS = 46,
        KETMIT = 47,
        SENDURL = 48,
        FORWARDX = 49,
        None = 0xFF
    }
}
